modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/GravelMiner/issues"

[[mods]]
modId="gravelminer"
version="${mod_version}"
displayName="GravelMiner"
displayURL="https://mods.twelveiterations.com/mc/gravelminer"
logoFile="gravelminer-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Automatically (insta-)mines falling gravel blocks that get in your way while mining.
'''

[[dependencies.gravelminer]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelminer]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelminer]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
